### ISSUE TITLE
Administrator login, CAS access callback

### ISSUE THREAD

**Issue by michburger** [sassoftware/restaf#119]
Dear restaf developers,
in my current projects, I've got issues with CAS data access as soon as I'm logged in as administrator.
How can I workaround that the CAS data does not arrive directly but a question related whether I'd like to access CAS as administrator is calling back and no data can be loaded? Actually in the relevant projects it would be great having the possibility to switch to administrator mode as data would be accessible this way only for administrators who are checking issues from users.

**Comment by devaKumaraswamy** [comment]
@michburger 
1. When you logged on to Viya, did you answer  in the positive to a prompt similar to the picture below
![image](https://github.com/user-attachments/assets/587a3c23-51d4-4caa-abfb-f70aad468bbb)
This dialog might look different in your case based on how Viya was configured?

2.  What is the prompt you see when the code tries to read a cas table?

Note: restaf itself is not aware of access rights. It assumed that the Viya API's will handle all such issues.

**Comment by michburger** [comment]
Dear devakumaraswamy,it is no visible prompt. The result of a cas query contains some query and restaf simply cannot proceed.Will send you the details tomorrow.Michael Michael Burger SoftMatch.net
-------- Ursprüngliche Nachricht --------Von: devakumaraswamy ***@***.***> Datum: 20.10.24  16:36  (GMT+01:00) An: sassoftware/restaf ***@***.***> Cc: Michael Burger ***@***.***>, Mention ***@***.***> Betreff: Re: [sassoftware/restaf] Administrator login, CAS access callback (Issue #119) 
@michburger


When you logged on to Viya, did you answer  in the positive to a prompt similar to the picture below
image.png (view on web)
This dialog might look different in your case based on how Viya was configured?


What is the prompt you see when the code tries to read a cas table?


Note: restaf itself is not aware of access rights. It assumed that the Viya API's will handle all such issues.

**Comment by devaKumaraswamy** [comment]
Want to add a data point: If the table has access rights specified, the admin user does not have "super-power" to access the tables. This makes sense - since folks who do Viya administration are not usually permitted to see business data.

**Comment by michburger** [comment]
Seems that the issue got resolved with an update from SAS Viya ...
I mean if I'm logged on as administrator, there is no need for other ask back.

**Comment by michburger** [comment]
I could reproduce:
as administrator CAS is asking whether I'd like to elevate but using restaf I cannot answer:

{
  "auth_request": {
    "clientId": "sas.casControl",
    "scope": [
      "openid",
      "uaa.user",
      "SASAdministrators"
    ],
    "requestParameters": {
      "response_type": "code",
      "redirect_uri": "/casManagement/",
      "state": "dd5b4750-c990-4b4d-93a7-02101d053f12",
      "client_id": "sas.casControl"
    },
    "approvalParameters": {},
    "state": "dd5b4750-c990-4b4d-93a7-02101d053f12",
    "responseTypes": [
      "code"
    ],
    "resourceIds": [
      "sas.casControl",
      "openid",
      "uaa"
    ],
    "authorities": [
      {
        "authority": "uaa.resource"
      },
      {
        "authority": "sasapp"
      }
    ],
    "approved": false,
    "redirectUri": "/casManagement/",
    "extensions": {}
  },
  "approved_scopes": [],
  "denied_scopes": [
    {
      "code": "scope.SASAdministrators",
      "text": "SASAdministrators"
    }
  ],
  "options": {
    "confirm": {
      "path": "/SASLogon/oauth/authorize",
      "location": "https://sdtb-viya-emea.siemens-healthineers.com/SASLogon/oauth/authorize",
      "value": "true",
      "key": "user_oauth_approval"
    },
    "deny": {
      "path": "/SASLogon/oauth/authorize",
      "location": "https://sdtb-viya-emea.siemens-healthineers.com/SASLogon/oauth/authorize",
      "value": "false",
      "key": "user_oauth_approval"
    }
  },
  "redirect_uri": "/casManagement/",
  "undecided_scopes": [],
  "scopes": [
    {
      "code": "scope.SASAdministrators",
      "text": "SASAdministrators"
    }
  ],
  "message": "To confirm or deny access POST to the following locations with the parameters requested.",
  "client_display_name": "sas.casControl"
}

**Comment by michburger** [comment]
restaf.min.js:7  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at restaf.min.js:7:38813
    at e.a (restaf.min.js:7:39141)
    at restaf.min.js:1:79106

**Comment by devaKumaraswamy** [comment]
@michburger  I do not quite follow your responses.

1. what did the updated Viya fix?
2. is the last message after the update? The error usually happens when the response from Viya is something that looks like ok to restaf but is not - so I am guessing the access is not working.
3. does it work if you logon as a user who is authorized to access the table?

**Comment by devaKumaraswamy** [comment]
@michburger 
can you comment on my questions?
Want to make sure your issue is resolved.

Thanks...
Deva

**Comment by michburger** [comment]
Dear Deva,
unfortunately I was wrong: The issue is not fixed.

Typically, the problem shows up in Edge and in the Console I can find this output when working as Administrator in Viya:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at restaf.min.js:7:38813
    at e.a (restaf.min.js:7:39141)
    at restaf.min.js:1:79106

The background: We've created a custom frontend as an IFrame / WebContent in the Viya report. That means, we're using the Viya login and host an additional web part inside.
That means, my administrator login is valid for restaf.

For this case, restaf seems not yet to be prepared:

                "/casManagement/" !== t.href && "/casManagement" !== t.href || "GET" !== t.method || (e.data.results.links = e.data.results.links.map((function(t) {
                    return "collection" === t.rel && (t.title = "servers",
                    t.rel = "servers",
                    t.patch = "cas"),
                    t
                }


The problem is with this check in the first line because in this situation the variables are set as:
t.method: "GET"
t.href: "/casManagement/"
e.status: 200
e.data.results.links is undefined - which causes the whole process to stop here.

the e.data.results object actually is a query related to admin access:

{
    "auth_request": {
        "clientId": "sas.casControl",
        "scope": [
            "openid",
            "uaa.user",
            "SASAdministrators"
        ],
        "requestParameters": {
            "response_type": "code",
            "redirect_uri": "/casManagement/",
            "state": "1b9a6562-95d1-48c6-a5df-2c75a4ff15d9",
            "client_id": "sas.casControl"
        },
        "approvalParameters": {},
        "state": "1b9a6562-95d1-48c6-a5df-2c75a4ff15d9",
        "responseTypes": [
            "code"
        ],
        "resourceIds": [
            "sas.casControl",
            "openid",
            "uaa"
        ],
        "authorities": [
            {
                "authority": "uaa.resource"
            },
            {
                "authority": "sasapp"
            }
        ],
        "approved": false,
        "redirectUri": "/casManagement/",
        "extensions": {}
    },
    "approved_scopes": [],
    "denied_scopes": [
        {
            "code": "scope.SASAdministrators",
            "text": "SASAdministrators"
        }
    ],
    "options": {
        "confirm": {
            "path": "/SASLogon/oauth/authorize",
            "location": "https://sdtb-viya-emea.siemens-healthineers.com/SASLogon/oauth/authorize",
            "value": "true",
            "key": "user_oauth_approval"
        },
        "deny": {
            "path": "/SASLogon/oauth/authorize",
            "location": "https://sdtb-viya-emea.siemens-healthineers.com/SASLogon/oauth/authorize",
            "value": "false",
            "key": "user_oauth_approval"
        }
    },
    "redirect_uri": "/casManagement/",
    "undecided_scopes": [],
    "scopes": [
        {
            "code": "scope.SASAdministrators",
            "text": "SASAdministrators"
        }
    ],
    "message": "To confirm or deny access POST to the following locations with the parameters requested.",
    "client_display_name": "sas.casControl"
}

**Comment by devaKumaraswamy** [comment]
@michburger 
I and several folks run restaf based apps in webcontent.

 You need to make sure that the logon information to restaf is set properly.
When running under webcontent, This is the code I use:


```
let logonPayload = { 
  host: "your viya server url",
  authType: "server"
}

let store = restaf.initStore({casProxy: true});
let msg = await store.logon(logonPayload);
let {casManagement} = await store.addServices('casManagement');

```

is your code  similar to this?

**Comment by michburger** [comment]
Dear Deva,
the code of the respective dashboards has two differences:
- store.logon had no await but similar parameters
- await store.addServices('identities') instead of await store.addServices('casManagement')

would one or both changes correct the behavior?

**Comment by devaKumaraswamy** [comment]
Michael:
1. store.logon is an async function since it might(in some circumstances) call other services. So an await is needed. 
2. Since you are using cas, you need to change addServices as follows:
let r = await store.addServices('identities', 'casManagement'); Otherwise there is no links to cas services setup in the store. I am assuming you are calling identities to get the user name. It is ok to call addServices on the same service multiple times - restaf will reuse what is already there. 

Data point:
Viya changed the default settings for CORS. This has caused issues for me. Still working with developers to understand why the new settings cause issues with access from user apps. So I set the defaults to the old default. But you should talk to your Viya admin about it. Below is my CORS setting.
![image](https://github.com/user-attachments/assets/a6b884b7-958b-4784-8f07-3f0a63240307)

**Comment by devaKumaraswamy** [comment]
Additional comments - using Firefox: 
Firefox has additional security defaults that prevents writing cookies. So here is some info on how to deal with it:
----
Click the shield icon to the left of the address bar.
Select “Turn off Enhanced Tracking Protection” for that site.

**Comment by michburger** [comment]
Dear Deva,
I think there is a misunderstanding: In the case that I'm not working with the 'Authorize Access' setting, i.e., not working with elevated permissions, the code runs fine.

But in the case, elevated access is chosen, this JSON does not conform with the expectation of restaf. That's why I asked you here in this issue for a solution.

actually, the problem starts with a call to

let services = await store.addServices('casManagement', 'reports', 'reportTransforms');

**Comment by devaKumaraswamy** [comment]
Michael:
 I was able to reproduce the issue with a newer version of Viya
This change to initStore helped my test app:

let store = restaf.initStore({casProxy: true});

let me know if it works.

**Comment by michburger** [comment]
Dear Deva,
our current code always uses with initStore variant. But we've always got this problem.

**Comment by devaKumaraswamy** [comment]
Here is a test app that you can deploy the same way you are deploying the failing app. See what happens.

1. change the extension to html
2. Edit file and change 'MICHAEL_SERVER" to your viya url.
3. deploy it to the same location as your failing app.
4. add the url of this app to the webcontent and try it.
This works for me, whether i logon as admin or not, but that is a just data [point.]

let me know what happens
[micburger.txt](https://github.com/user-attachments/files/17587781/micburger.txt)

Just covering bases:

Not sure of all your settings, but one new wrinkle in Viya is that the sas.commons.web.security's content security policy must look something like this:

default-src 'self'; style-src 'self'; font-src 'self' data:; frame-ancestors 'self'; form-action 'self' your-cors-allowed-origins;

The your-cors-allowed origins but without the commas replaced by blank. My setting looks like this:

default-src 'self'; style-src 'self'; font-src 'self' data:; frame-ancestors 'self'; form-action 'self' https://localhost:8080 https://someweb.core.windows.net;

**Comment by michburger** [comment]
Dear Deva,
yes, that is working without a problem. The callback issue just happens when I actually load CAS data towards the frontend.

**Comment by michburger** [comment]
Oh, after replacing MICHAEL_SERVER with the complete protocol prefix, I get
ready


redirs:
{
    "msg": "redirects completed"
}


file service:
{}

compute service:
{
    "status": 400,
    "statusText": "Request failed with status code 400",
    "detail": "{\"version\":2,\"httpStatusCode\":400,\"errorCode\":5854,\"message\":\"The attempt to run a Compute server as the user \\\"z0046trh\\\" failed because a service account credential could not be found for that user.\",\"details\":[\"path: /compute/contexts/ad76848d-01a3-418f-a8ab-b6b84342e82a/sessions\",\"correlator: b7083128-1309-4453-ae23-406f2642e222\"]}",
    "error": true
}

(an issue with the context)

cas echo:

{
    "metrics": {
        "cpuUserTime": 0,
        "memory": 233760,
        "ioReadBlocks": 0,
        "systemNodes": 1,
        "cpuSystemTime": 0.000521,
        "osMemory": 16674816,
        "systemCores": 64,
        "ioPageFaults": 0,
        "elapsedTime": 0.000556,
        "ioReadFaults": 0,
        "ioReadBytes": 0,
        "systemMemory": 0,
        "voluntaryContextSwitches": 0,
        "dataMovementBytes": 0,
        "ioWriteBytes": 0,
        "involuntaryContextSwitches": 0,
        "systemTotalMemory": 541027733504,
        "memoryQuota": 16674816,
        "ioReadCalls": 0,
        "ioWriteCalls": 0,
        "ioPageReclaims": 0,
        "ioWriteBytesCancelled": 0
    },
    "log": "NOTE: builtin.echo called with 1 parameters.\nNOTE:    parameter 1: code = {x = 1}\n",
    "tables": {},
    "tablesByName": {},
    "logEntries": [
        {
            "level": "info",
            "message": "NOTE: builtin.echo called with 1 parameters."
        },
        {
            "level": "info",
            "message": "NOTE:    parameter 1: code = {x = 1}"
        }
    ],
    "changedResources": [
        "caslibs",
        "tables",
        "actionsets",
        "datasources",
        "caslibPermissions",
        "actionPermissions",
        "administrators",
        "BWList"
    ],
    "status": 0,
    "results": {
        "code": {
            "x": 1
        }
    },
    "disposition": {
        "debugInfo": null,
        "formattedStatus": null,
        "reason": "OK",
        "severity": "Normal",
        "statusCode": 0
    }
}



rest call:

{
    "message": "Network Error",
    "name": "AxiosError",
    "stack": "AxiosError: Network Error\n    at f.onerror (https://unpkg.com/@sassoftware/restaf@5.2.4:7:56878)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*"
        },
        "method": "get",
        "url": "http://localhost:3000/api/test",
        "withCredentials": true
    },
    "code": "ERR_NETWORK",
    "status": null
}

**Comment by devaKumaraswamy** [comment]
Michael:
 1. **cas seems to be working - which was the original problem - so not sure why your app is failing.**
 2. A note on compute: Sounds like there are other restrictions on using the compute service - not really sure what Viya is saying. You should talk to some compute service expert and/or your Viya admin.

 3.  The other options are failing/working as intended in this version of the test app.

So we are still left with the mystery as to why your app is failing...

Deva

**Comment by michburger** [comment]
Dear Deva,the app is not failing for non-admins.CAS data loading is failing for admins only. Please read again.Regards Michael Burger 
-------- Ursprüngliche Nachricht --------Von: devakumaraswamy ***@***.***> Datum: 31.10.24  18:22  (GMT+01:00) An: sassoftware/restaf ***@***.***> Cc: Michael Burger ***@***.***>, Mention ***@***.***> Betreff: Re: [sassoftware/restaf] Administrator login, CAS access callback (Issue #119) 
Michael:


cas seems to be working - which was the original problem - so not sure why your app is failing.


A note on compute: Sounds like there are other restrictions on using the compute service - not really sure what Viya is saying. You should talk to some compute service expert and/or your Viya admin.


The other options are failing/working as intended in this version of the test app.


So we are still left with the mystery as to why your app is failing...
Deva

**Comment by devaKumaraswamy** [comment]
Michael:
I have apps that read and update cas tables when logged on with or without admin rights.
As I recall you could not get past addServices('casManagement') - so unclear how you are saying it is the access to cas tables.

can you explain how you are reading the cas tables.
can you share a snippet of the code that is accessing data?
cheers...
Deva

**Comment by devaKumaraswamy** [comment]
Replace the runCas in the test app to this.. it does a simple read.

async function runCas(store) {
        let { casManagement } = await store.addServices("casManagement");
        let servers = await store.apiCall(casManagement.links("servers"));
        let serverName = servers.itemsList(0);
        let session = await store.apiCall(
          servers.itemsCmd(serverName, "createSession")
        );
        let payload = {
          action: "builtins.echo",
          data: { code: { x: 1 } },
        };
        console.log(JSON.stringify(session.links("execute"), null, 4));
        let r = await store.runAction(session, payload);
        console.log("echo completed");
        debugger;
        payload = {
          from: 1,
          count: 20,
          format: true,
          table: { caslib: "Samples", name: "COSTCHANGE" },
        };
        let actionPayload = {
          action: "table.fetch",
          data: { table: { caslib: "Samples", name: "COSTCHANGE" } },
        };
        debugger;
        let actionResult = await store.runAction(session, actionPayload);
        console.log("------------------ results from fetch");

        console.log(JSON.stringify(actionResult.items("tables"), null, 4));
        console.log(JSON.stringify(actionResult.items("tableNames"), null, 4));
        await store.apiCall(session.links("delete"));
        return actionResult.items("tables");
      }

**Comment by devaKumaraswamy** [comment]
Michael:
Want to reiterate:
 restaf itself has no visibility into the authorization rules for assets/apis. So if the call fails for an admin user only, then I would look for any authorization rules that are in play. 
Deva

**Comment by michburger** [comment]
Dear Deva,
not really sure why: The issue is gone now. It might be connected with adding 'casManagement' more frequently or with some other sort of CAS crash we had in parallel.

**Comment by devaKumaraswamy** [comment]
@michburger 

  Glad to hear the issue is gone but wish we knew why it failed before.
   I will close this ticket. 
 Thanks for being a user of restaf.
Cheers...
Deva
